name: image_form_field
description: Pretty time formatting for pretty code
version: 0.0.1
homepage: https://github.com/tshedor/time_ago
author: Tim Shedor<opensource@timshedor.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.4.10
